---
kind: pipeline
type: docker
name: test_trading_board

platform:
  os: linux
  arch: amd64

x-generic_environment: &common_environment
    DRONE_DOCKER_CONFIG: "/root/.docker/config.json"

x-generic-step-volume: &generic_step_volume
  - name: "docker_socket"
    path: "/var/run/docker/sock"
  - name: "shared_memory"
    path: "/dev/shm"

x-generic-publish-settings: &generic_publish_settings
    username:
        from_secret: "DOCKER_USERNAME"
    password:
        from_secret: "DOCKER_PASSWORD"
    pushtags: "true"
    login: "true"
    registry: "madwaks"

services:
    - name: postgresql
      image: bitnami/postgresql:latest
      environment:
          POSTGRESQL_USERNAME: postgresql
          POSTGRESQL_PASSWORD: atporder
          POSTGRESQL_DATABASE: tradingboard
      ports:
        - 27017

triggers:
    branch:
        include:
            - master
    event:
        - push

steps:
  - name: fr
    image: alpine
    commands:
      - echo bonjour monde
    when:
      branch:
          - master
          - develop
    volumes:
      - name: docker_socket
        path: "/var/run/docker/sock"
      - name: shared_memory
        path: "/dev/shm"
