# Generated by Django 3.1.5 on 2021-01-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Portfolio",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.FloatField()),
                ("name", models.CharField(default="New Portfolio", max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "type",
                    models.CharField(
                        choices=[("Buy", "ACHAT"), ("Sell", "VENTE")], max_length=128
                    ),
                ),
                ("open_price", models.FloatField(default=0.0)),
                ("close_price", models.FloatField(default=0.0)),
                (
                    "portfolio",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="trading_board.portfolio",
                    ),
                ),
            ],
        ),
    ]
